name: sub

on:
  workflow_call:

jobs:
  show-secret-variables:
    name: show-secret-variables
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          echo "${{ github.event.inputs.secrets_list }}" | while IFS='=' read -r key value; do
            echo "$key=$value" >> $GITHUB_ENV
          done
      - name: Print environment variables
        run: |
          echo "Environment Variables:"
          env